"""Description of changes

Revision ID: 4a97fd9fab9c
Revises: 
Create Date: 2023-08-28 16:41:48.403615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a97fd9fab9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(length=5), nullable=False),
    sa.Column('booked_by', sa.String(length=50), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('resource_id', 'time_slot', 'booking_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    # ### end Alembic commands ###
